### ISSUE TITLE
Add new component - Google Web Designer Components

### ISSUE THREAD

**Issue by niutech** [webcomponents/customelements.io#391]
A set of Web Components included in Google Web Designer: https://github.com/niutech/gwdcomponents

**Comment by zenorocha** [comment]
Have you considered using [Bower](http://bower.io/) or [npm](https://www.npmjs.com/)? We strongly recommend using one of them to distribute your element. If you use the `web-components` keyword in your `bower.json` or `package.json` file, then we'll automatically fetch it here.

**Comment by niutech** [comment]
Added `bower.json`.

**Comment by zenorocha** [comment]
http://customelements.io/?q=niutech ;D

**Comment by niutech** [comment]
Thanks!
