### ISSUE TITLE
Add new component - paper-chip

### ISSUE THREAD

**Issue by bendavis78** [webcomponents/customelements.io#398]
https://github.com/bendavis78/paper-chip

**Comment by zenorocha** [comment]
Hey @bendavis78, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by bendavis78** [comment]
Done!

**Comment by zenorocha** [comment]
http://customelements.io/?q=paper-chip ;)
