### ISSUE TITLE
Add new component - client-uuid

### ISSUE THREAD

**Issue by pope** [webcomponents/customelements.io#407]
https://github.com/pope/client-uuid

**Comment by zenorocha** [comment]
Hey @pope, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by pope** [comment]
Perfect. Done and done.

**Comment by zenorocha** [comment]
http://customelements.io/?q=client-uuid
