### ISSUE TITLE
Add new component - gravatar-polymer-profile

### ISSUE THREAD

**Issue by vanxrice** [webcomponents/customelements.io#408]
https://github.com/vanxrice/gravatar-polymer-profile

**Comment by zenorocha** [comment]
Hey @vanxrice, thanks for submitting!

It was automagically added since you included the `web-components` keyword in your `bower.json` file :)

http://customelements.io/?q=vanxrice

**Comment by vanxrice** [comment]
@zenorocha awesome! Thanks!
