### ISSUE TITLE
Add new component - x-playlist

### ISSUE THREAD

**Issue by heff** [webcomponents/customelements.io#413]
https://github.com/heff/x-playlist

**Comment by zenorocha** [comment]
Hey @heff, thanks for submitting!

It was automagically added since you included the `web-components` keyword in your `bower.json` file :)

http://customelements.io/?q=x-playlist

**Comment by heff** [comment]
​Aha! Thanks.

**Comment by heff** [comment]
The [search](http://customelements.io/?q=x-playlist) no longer brings up x-playlist. Did something break, or should I resubmit it?

**Comment by zenorocha** [comment]
It was probably some downtime, it's back again ;)

**Comment by heff** [comment]
Cool, thanks!
