### ISSUE TITLE
Add new component - process-arrow

### ISSUE THREAD

**Issue by ohanhi** [webcomponents/customelements.io#418]
https://github.com/futurice/process-arrow

![](https://github.com/futurice/process-arrow/raw/master/docs/example.png)

**Comment by zenorocha** [comment]
Hey @ohanhi, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by ohanhi** [comment]
@zenorocha, registered!

![screenshot from 2015-02-03 13 29 53](https://cloud.githubusercontent.com/assets/8436403/6019404/d1efb0bc-aba8-11e4-95f1-07a69ecc4805.png)

**Comment by zenorocha** [comment]
http://customelements.io/?q=futurice ;D
