### ISSUE TITLE
Add new component - 

### ISSUE THREAD

**Issue by kysonic** [webcomponents/customelements.io#420]
https://github.com/kysonic/x-tips-overlay-dev/

**Comment by zenorocha** [comment]
Hey @kysonic, thanks for submitting!

Since you're using Bower, now you just need to add the `web-components` keyword in your `bower.json` file and make sure it is registered:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by kysonic** [comment]
I get it. Thanks!

2015-01-31 15:05 GMT+03:00 Zeno Rocha <notifications@github.com>:

**Comment by zenorocha** [comment]
Still haven't been published to Bower...

**Comment by kysonic** [comment]
I'm have a problems with registration. I make it before, but now bower responded 403.

**Comment by zenorocha** [comment]
http://customelements.io/?q=kysonic ;D

**Comment by kysonic** [comment]
Thanks!

2015-02-16 14:06 GMT+03:00 Zeno Rocha <notifications@github.com>:
