### ISSUE TITLE
Add new component - polymer-daterange

### ISSUE THREAD

**Issue by DominicBoettger** [webcomponents/customelements.io#423]
A date range picker in material style.

https://github.com/inspirationlabs/polymer-daterange

**Comment by zenorocha** [comment]
Hey @DominicBoettger, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by DominicBoettger** [comment]
Hey @zenorocha,

it's already available via bower.
https://bower.io/search/?q=polymer-daterange

Or is something else still missing?

Best regards
Dominic

**Comment by zenorocha** [comment]
http://customelements.io/?q=polymer-daterange ;D
