### ISSUE TITLE
Add new component - font-awesome

### ISSUE THREAD

**Issue by baclap** [webcomponents/customelements.io#424]
https://github.com/baclap/font-awesome

**Comment by zenorocha** [comment]
Hey @baclap, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by baclap** [comment]
So I've registered the element already but I had to use `baclap-font-awesome` as the package name since `font-awesome` was already taken.

**Comment by zenorocha** [comment]
http://customelements.io/?q=baclap ;D
