### ISSUE TITLE
Add new component - DateRangeHTML5WebControl

### ISSUE THREAD

**Issue by TalalTayyab** [webcomponents/customelements.io#426]
https://github.com/TalalTayyab/DateRangeHTML5WebControl/tree/master/DateRangeHTML5WebControl

**Comment by zenorocha** [comment]
Hey @TalalTayyab, thanks for submitting!

Since you're using Bower, now you just need to add the `web-components` keyword in your `bower.json` file and make sure it is registered:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by TalalTayyab** [comment]
@zenorocha  done, thanks for the info.

**Comment by zenorocha** [comment]
http://customelements.io/?q=Talal ;D
