### ISSUE TITLE
Add new component - nb-menu

### ISSUE THREAD

**Issue by sup3rb0wlz** [webcomponents/customelements.io#428]
https://github.com/sup3rb0wlz/nb-menu

**Comment by zenorocha** [comment]
Hey @sup3rb0wlz, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by zenorocha** [comment]
http://customelements.io/?q=nb-menu ;D

**Comment by sup3rb0wlz** [comment]
Thank you, I think it just took a little bit
