### ISSUE TITLE
Add new component - ist-image-map

### ISSUE THREAD

**Issue by nothnk** [webcomponents/customelements.io#432]
Simple web component to create a static image maps (gmaps or opentstreetmaps) using Polymer. https://github.com/Isiat/ist-image-map

**Comment by zenorocha** [comment]
http://customelements.io/?q=ist-image-map ;D

**Comment by zenorocha** [comment]
Hey @nothnk, thanks for submitting!

It was automagically added since you included the `web-components` keyword in your `bower.json` file :)

http://customelements.io/?q=ist-image-map ;D
