### ISSUE TITLE
Add new component - polymer-il-charts

### ISSUE THREAD

**Issue by DominicBoettger** [webcomponents/customelements.io#433]
https://github.com/INSPIRATIONlabs/polymer-il-charts

**Comment by zenorocha** [comment]
Hey @DominicBoettger, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by DominicBoettger** [comment]
Hey @zenorocha,

sorry that i forgot to register. I did that now.

Best regards
Dominic
