### ISSUE TITLE
Add new component - word-pronunciation

### ISSUE THREAD

**Issue by adolfov** [webcomponents/customelements.io#434]
https://github.com/adolfov/word-pronunciation

**Comment by zenorocha** [comment]
Hey @adolfov, thanks for submitting!

Since you're using Bower, now you just need to add the `web-components` keyword in your `bower.json` file and make sure it is registered:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by adolfov** [comment]
Done :) Thank you Zeno!

**Comment by zenorocha** [comment]
http://customelements.io/?q=adolfov ;D
