### ISSUE TITLE
Add new component - imgur-upload

### ISSUE THREAD

**Issue by ianbibby** [webcomponents/customelements.io#435]
https://github.com/ianbibby/imgur-upload

**Comment by zenorocha** [comment]
Hey @ianbibby, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by ianbibby** [comment]
Ah cool.  I just did that and it looks like it registered successfully.  

Thanks! :)

**Comment by zenorocha** [comment]
Yep, http://customelements.io/?q=imgur-upload ;D
