### ISSUE TITLE
Add new component - px-slides

### ISSUE THREAD

**Issue by ngduc** [webcomponents/customelements.io#439]
https://github.com/ngduc/px-slides

**Comment by zenorocha** [comment]
Hey @ngduc, thanks for submitting!

Since you're using Bower, now you just need to add the `web-components` keyword in your `bower.json` file and make sure it is registered:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by ngduc** [comment]
Thanks @zenorocha , I can see "px-slides" on the website now.

**Comment by zenorocha** [comment]
;D
