### ISSUE TITLE
Add new component - web-presentation

### ISSUE THREAD

**Issue by ChristianKohler** [webcomponents/customelements.io#442]
https://github.com/ChristianKohler/web-presentation

**Comment by zenorocha** [comment]
Hey @ChristianKohler, thanks for submitting!

Since you're using Bower, now you just need to add the `web-components` keyword in your `bower.json` file and make sure it is registered:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by ChristianKohler** [comment]
Hi @zenorocha 

I added the web-components keyword and added the package to bower registry.

Chris

**Comment by zenorocha** [comment]
We only fetch `web-components` keywords, not `web components`.

**Comment by ChristianKohler** [comment]
Ok. I added the keyword. Now it works. Thank you.
