### ISSUE TITLE
Add new component - login form

### ISSUE THREAD

**Issue by youssef06** [webcomponents/customelements.io#444]
https://github.com/youssef06/polymer-login-form

**Comment by zenorocha** [comment]
Hey @youssef06, thanks for submitting!

Since you're using Bower, now you just need to add the `web-components` keyword in your `bower.json` file and make sure it is registered:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by youssef06** [comment]
Done, Thanks @zenorocha.

**Comment by zenorocha** [comment]
http://customelements.io/?q=login-form
