### ISSUE TITLE
Add new component - fixmetodo

### ISSUE THREAD

**Issue by ondras** [webcomponents/customelements.io#448]
https://github.com/ondras/fixmetodo

**Comment by zenorocha** [comment]
Hey @ondras, thanks for submitting!

Since you're using Bower, now you just need to add the `web-components` keyword in your `bower.json` file and make sure it is registered:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by ondras** [comment]
Hi @zenorocha,

thanks for getting to me so fast. I adjusted the `bower.json` with the proper keyword. Now I assume the next syncing cronjob will do the magic?

**Comment by zenorocha** [comment]
Yep ;)

**Comment by ondras** [comment]
Added, fixed, thanks!
