### ISSUE TITLE
Add new component - polymer-component-animated-selector

### ISSUE THREAD

**Issue by kalpeshbeit** [webcomponents/customelements.io#449]
https://github.com/ShubanTech/polymer-component-animated-selector

**Comment by zenorocha** [comment]
Hey @kalpeshbeit, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by kalpeshbeit** [comment]
I had already registered

**Comment by zenorocha** [comment]
http://customelements.io/?q=shuban ;D

**Comment by kalpeshbeit** [comment]
Thanks

**Comment by kalpeshbeit** [comment]
Hey zeno,

                  Why i am not able to use jquery inside Polymer element .

Also i found if i use jquery its working fine in mozilla and not works in
google  crome.

**Comment by zenorocha** [comment]
You should fill an issue in the Polymer project, this isn't the proper place to do so.

**Comment by kalpeshbeit** [comment]
Ok
