### ISSUE TITLE
Add new component - fork-me-on-github

### ISSUE THREAD

**Issue by tcyrus** [webcomponents/customelements.io#450]
https://github.com/tcyrus/fork-me-on-github

**Comment by zenorocha** [comment]
Hey @tcyrus, thanks for submitting!

Since you're using Bower, now you just need to add the `web-components` keyword in your `bower.json` file and make sure it is registered:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by tcyrus** [comment]
Done
