### ISSUE TITLE
Add new component - lorem-ipsum-tag

### ISSUE THREAD

**Issue by phoenixstormcrow** [webcomponents/customelements.io#455]
https://github.com/phoenixstormcrow/lorem-ipsum-tag

Doesn't seem to be showing up in search on customelements.io, but published to npm 2 days ago. How often does the registry get scanned?

**Comment by zenorocha** [comment]
http://customelements.io/?q=lorem-ipsum ;D

**Comment by zenorocha** [comment]
Btw, good job! I'll share it with the @webcomponents account on twitter

**Comment by phoenixstormcrow** [comment]
Thanks! I was really just curious as to why it's not showing up on the site; while I like my component, and use it quite a bit, I realize that there only needs to be so many of the same thing :)
