### ISSUE TITLE
Add new component - checkbox-list

### ISSUE THREAD

**Issue by mohsen1** [webcomponents/customelements.io#460]
https://github.com/mohsen1/checkbox-list

**Comment by zenorocha** [comment]
Hey @mohsen1, thanks for submitting!

Since you're using npm, now you just need to add the `web-components` keyword in your `package.json` file and make sure it is registered:

```sh
$ npm publish
```

**Comment by mohsen1** [comment]
done. https://github.com/mohsen1/checkbox-list/blob/master/package.json#L37

**Comment by zenorocha** [comment]
http://customelements.io/?q=checkbox-list ;D
