### ISSUE TITLE
Add new component - polymer-seed

### ISSUE THREAD

**Issue by grvcoelho** [webcomponents/customelements.io#462]
https://github.com/grvcoelho/polymer-seed

**Comment by zenorocha** [comment]
Hey @grvcoelho, thanks for submitting!

Since you're using Bower and already added the `web-components` keyword in your `bower.json` file, now you just need to register it:

```sh
$ bower register <my-package-name> <git-endpoint>
```

**Comment by grvcoelho** [comment]
Didn't know about that.

Done and thanks :smile:

**Comment by zenorocha** [comment]
It's described on the homepage ;)
